
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-4pm-3
owner: ucsb-cs156-s24
repo_name: team02-s24-4pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjM4NzAyMjEx","is_bot":false,"login":"tim-choi","name":"Timothy Choi"},"headRefName":"TC-ArticlesController-db","number":65,"title":"Issue: Create ArticlesController, add GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-3/pull/65"},{"author":{"id":"MDQ6VXNlcjYxNjY4MzI3","is_bot":false,"login":"KevinChen0527","name":"Kevin Chen"},"headRefName":"KevinC-UCSBDiningCommonsMenuItemPut","number":64,"title":"Ucsb dining commons menu item put endpoint","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-3/pull/64"},{"author":{"id":"MDQ6VXNlcjYxNjY4MzI3","is_bot":false,"login":"KevinChen0527","name":"Kevin Chen"},"headRefName":"KevinC-UCSBDiningCommonsMenuItemDelete","number":62,"title":"Add delete endpoint to Dining Commons Menu Items Controller","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-3/pull/62"},{"author":{"id":"MDQ6VXNlcjQyOTg1Njg3","is_bot":false,"login":"ericpretzel","name":"Eric W"},"headRefName":"Eric-HelpRequestControllerPut","number":51,"title":"HelpRequestController PUT single entry by id with tests","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-3/pull/51"},{"author":{"id":"MDQ6VXNlcjUxODg2NTU1","is_bot":false,"login":"coder626","name":""},"headRefName":"coder626-UCSBOrganization-create-db","number":49,"title":"create database table on dokku for ucsb organization","url":"https://github.com/ucsb-cs156-s24/team02-s24-4pm-3/pull/49"}]
